### ISSUE TITLE
[BUG] Players can escape the lobby.

### ISSUE THREAD

**Issue by Moesh** [Moesh/Revolution#1]
**Describe the bug**
Players can escape the lobby through several methods.

**To Reproduce**:
Method 1:
1. Set yourself on fire at [204 100 214]
2. Join the red team by right-clicking the sign
3. Crouch next to the nether fences facing the level
4. Jump as the fire damage hits
5. The player is able to get over the Nether Fence.

Method 2:
1. Join the game with another player
2. Find a 1.5 block high barrier
3. Have one player punch the other player as they jump for extra height

**Current behavior**
Players are able to escape the lobby and damage the level's integrity by removing or exchanging items in chests.

**Expected behavior**
Players are not able to alter the map in any way before the game begins.

**Game version**
 - Version 1.15.1

**Comment by Moesh** [comment]
Reported by Flytre and Vilder50

**Comment by Flytre** [comment]
Method 3:
Go into the lava in the lobby. Climb up the ladder and use fire to jump the fence. Parkour around the wall and enter the arena from the wall.
![2020-01-11_13 54 29](https://user-images.githubusercontent.com/40476907/72209239-3189f280-347a-11ea-8f12-4a2d92fa6c87.png)
![2020-01-11_13 54 45](https://user-images.githubusercontent.com/40476907/72209240-3189f280-347a-11ea-8e33-12a69bb7a9fd.png)

**Comment by Flytre** [comment]
Untested but probable Method 4:
Save a boat in your inventory by storing it in the crafting grid and use it to get through the fences.

**Comment by Moesh** [comment]
Will be fixed by teleporting all players back to spawn.
